name = "Frame2TM"
version = "0.1.0"
license = "license"
author = "lidaltonlima"
maintainer = "lidaltonlima@gmail.com"
copyright = "Copyright 2026, lidaltonlima"

[fortran]
source-form = "default"
implicit-typing = true
implicit-external = true

[[executable]]
name = "main"
